# Cargo config file. 
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="axum_todo_app=debug"



# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER="web-folder/"